### ISSUE TITLE
请问一下

### ISSUE THREAD

**Issue by aaaasssdd** [yicaoyimuys/GoGameServer#3]
这个框架现在在实际项目中使用了吗？多谢

**Comment by yicaoyimuys** [comment]
这个结构在项目中用过的

**Comment by aaaasssdd** [comment]
php,nodejs,go现在你们的服务器都用吗？主要用哪个？

**Comment by aaaasssdd** [comment]
php感觉没什么优势，nodejs在H5游戏中有语言优势。

**Comment by yicaoyimuys** [comment]
做弱联网，后端只是进行数据记录或者统计的，用php的开发效率还是可以的，热更新
